-- ============================================================
-- Customer Shopping Behavior Analysis - SQL Queries
-- Author: Rajdeep Bose
-- Description: Analytical SQL queries (Q1 - Q10) analyzing customer
--              demographics, revenue drivers, subscription impact,
--              and purchasing behaviors.
-- ============================================================

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


-- ============================================================
-- ADVANCED ENTERPRISE ANALYTICS QUERIES (Q11 - Q14)
-- ============================================================

--Q11. Behavioral Customer Segmentation (RFM-Inspired NTILE Scoring)
WITH rfm_base AS (
    SELECT 
        customer_id,
        previous_purchases AS frequency,
        purchase_amount AS monetary,
        purchase_frequency_days AS recency_days
    FROM customer
),
rfm_scores AS (
    SELECT 
        customer_id,
        NTILE(5) OVER (ORDER BY recency_days ASC) AS r_score,
        NTILE(5) OVER (ORDER BY frequency DESC) AS f_score,
        NTILE(5) OVER (ORDER BY monetary DESC) AS m_score
    FROM rfm_base
)
SELECT 
    customer_id,
    r_score,
    f_score,
    m_score,
    (r_score + f_score + m_score) AS total_rfm_score,
    CASE 
        WHEN (r_score + f_score + m_score) >= 12 THEN 'Champions / VIP'
        WHEN (r_score + f_score + m_score) BETWEEN 9 AND 11 THEN 'Loyal Customers'
        WHEN (r_score + f_score + m_score) BETWEEN 6 AND 8 THEN 'Promising'
        ELSE 'At Risk / Needs Attention'
    END AS rfm_segment
FROM rfm_scores
ORDER BY total_rfm_score DESC
LIMIT 20;


--Q12. Cumulative Category Revenue Contribution & Share of Wallet
WITH category_revenue AS (
    SELECT 
        category,
        SUM(purchase_amount) AS category_revenue
    FROM customer
    GROUP BY category
)
SELECT 
    category,
    category_revenue,
    SUM(category_revenue) OVER (ORDER BY category_revenue DESC) AS cumulative_revenue,
    ROUND(100.0 * category_revenue / SUM(category_revenue) OVER (), 2) AS revenue_share_pct
FROM category_revenue
ORDER BY category_revenue DESC;


--Q13. Shipping Tier Profitability & Order Value Density Analysis
SELECT 
    shipping_type,
    COUNT(customer_id) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_usage_pct
FROM customer
GROUP BY shipping_type
ORDER BY total_revenue DESC;


--Q14. High-Value Customer Tiering & Engagement Ranking
SELECT 
    customer_id,
    age,
    gender,
    subscription_status,
    previous_purchases,
    purchase_amount,
    review_rating,
    CASE 
        WHEN previous_purchases >= 30 AND purchase_amount >= 75 THEN 'Tier 1 - High Value VIP'
        WHEN previous_purchases >= 15 AND purchase_amount >= 50 THEN 'Tier 2 - Growth Potential'
        WHEN previous_purchases < 15 AND purchase_amount >= 50 THEN 'Tier 3 - New High Spender'
        ELSE 'Tier 4 - Low Engagement'
    END AS clv_tier
FROM customer
ORDER BY purchase_amount DESC, previous_purchases DESC
LIMIT 25;


